const mongoose=require("mongoose");
const patientSchema=new mongoose.Schema({
    name:{
        type:String,
        min:3,
        max:20,
        default:""
    },
    email:{
        type:String,
        required:true,
        max:50,
        unique:true
    },
    phoneno:{
        type:String,
        default:"",
        max:10
    },
    age:{
        type:Number,
        default:0
    },
    dob:{
        type:String,
        default:"",
        max:10,
    },
    city:{
        type:String,
        default:"",
        min:50,
    },
    password:{
        type:String,
        required:true,
        min:6
    },
    pincode:{
        type:String,
        default:"",
        min:6
    },
    isGoogleSignIn:{
        type:Boolean,
        default:false,
        required:true
    },
    registerTime:{
        type:String,
        default:Date.now()
    },
    lastLoginTime:{
        type:String,
        default:Date.now(),
    },
    isRegistered:{
        type:Boolean,
        default:false,
        required:true
    },
    isSignedUp:{
        type:Boolean,
        default:false,
        requireD:true
    },
    isLoggedIn:{
        type:Boolean,
        default:false,
        required:true
    },
    type:{
        type:String,
        default:"patient"
    },
    startDate:{
        type:String,
        default:""
    },
    daysCompleted:{
        type:Number,
        default:0
    }


},{ timestamps:true })
module.exports=mongoose.model('patient',patientSchema)