const mongoose=require("mongoose");
const therapistSchema=new mongoose.Schema({
    name:{
        type:String,
        min:3,
        max:100,
        default:""
    },
    email:{
        type:String,
        required:true,
        max:50,
        unique:true
    },
    phoneno:{
        type:String,
        max:10,
        default:"",
    },
    dob:{   
        type:String,
        max:10,
        default:"",
    },
    city:{
        type:String,
        min:50,
        default:""
    },
    password:{
        type:String,
        required:true,
        min:6
    },
    hospitalname:{
        type:String,
        max:100,
        default:""
    },
    pincode:{
        type:String,
        min:6,
        default:""
    },
    isGoogleSignIn:{
        type:Boolean,
        default:false
    },
    registerTime:{
        type:String,
        default:Date.now()
    },
    lastLoginTime:{
        type:String,
        default:Date.now(),
    },
    isRegistered:{
        type:Boolean,
        default:false,
        required:true
    },
    isSignedUp:{
        type:Boolean,
        default:false,
        requireD:true
    },
    isLoggedIn:{
        type:Boolean,
        default:false,
        required:true
    },
    type:{
        type:String,
        default:"therapist"
    }


},{ timestamps:true })
module.exports=mongoose.model('therapist',therapistSchema)